name: build

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      - name: Build CLI
        run: make build-linux-amd64
      - name: run unit tests
        run: make test
      - name: Check version
        run: bin/linux/amd64/oras version
